In [1]:
# PROBLEM 1 — Student Scholarship Filter
# STEP 1: IMPORT LIBRARIES
import sqlite3
import pandas as pd

# STEP 2: CREATE DATABASE CONNECTION
conn = sqlite3.connect("student_scholarship.db")
cursor = conn.cursor()

# STEP 3: CREATE STUDENT TABLE
cursor.execute("""
CREATE TABLE IF NOT EXISTS STUDENT (
    StudentID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    City TEXT,
    Marks INTEGER,
    Course TEXT
)
""")

# STEP 4: INSERT AT LEAST 8 RECORDS
students = [
    (1, 'Arun', 'Chennai', 95, 'Python'),
    (2, 'Priya', 'Madurai', 88, 'Data Science'),
    (3, 'Kumar', 'Chennai', 76, 'Mathematics'),
    (4, 'Divya', 'Trichy', 92, 'History'),
    (5, 'Ravi', 'Madurai', 70, 'Python'),
    (6, 'Meena', 'Chennai', 85, 'Data Science'),
    (7, 'Suresh', 'Madurai', 98, 'Commerce'),
    (8, 'Anu', 'Chennai', 79, 'History'),
    (9, 'Bala', 'Madurai', 90, 'Commerce'),
    (10, 'Nila', 'Trichy', 82, 'Python')
]

cursor.executemany("""
INSERT OR REPLACE INTO STUDENT
(StudentID, Name, City, Marks, Course)
VALUES (?, ?, ?, ?, ?)
""", students)

conn.commit()

# STEP 5: DISPLAY ALL STUDENTS
print("ALL STUDENT RECORDS")

display(pd.read_sql_query("""
SELECT * FROM STUDENT
""", conn))

# STEP 6: DISTINCT COURSES
print("DISTINCT COURSES")

display(pd.read_sql_query("""
SELECT DISTINCT Course
FROM STUDENT
""", conn))

# STEP 7: SCHOLARSHIP FILTER
# City Chennai OR Madurai
# Marks BETWEEN 70 AND 95
# NOT enrolled in History
# Alias Name as Student_Name
# Order by Marks DESC
# Show TOP 5 students

print("TOP 5 SCHOLARSHIP STUDENTS")

display(pd.read_sql_query("""
SELECT
    StudentID,
    Name AS Student_Name,
    City,
    Marks,
    Course
FROM STUDENT
WHERE
    (City = 'Chennai' OR City = 'Madurai')
    AND Marks BETWEEN 70 AND 95
    AND NOT Course = 'History'
ORDER BY Marks DESC
LIMIT 5
""", conn))

# STEP 8: CLOSE DATABASE
conn.close()

print("Student Scholarship Filter Completed!")

ALL STUDENT RECORDS

   StudentID    Name     City  Marks        Course
0          1    Arun  Chennai     95        Python
1          2   Priya  Madurai     88  Data Science
2          3   Kumar  Chennai     76   Mathematics
3          4   Divya   Trichy     92       History
4          5    Ravi  Madurai     70        Python
5          6   Meena  Chennai     85  Data Science
6          7  Suresh  Madurai     98      Commerce
7          8     Anu  Chennai     79       History
8          9    Bala  Madurai     90      Commerce
9         10    Nila   Trichy     82        Python

DISTINCT COURSES

         Course
0        Python
1  Data Science
2   Mathematics
3       History
4      Commerce

TOP 5 SCHOLARSHIP STUDENTS

   StudentID Student_Name     City  Marks        Course
0          1         Arun  Chennai     95        Python
1          9         Bala  Madurai     90      Commerce
2          2        Priya  Madurai     88  Data Science
3          6        Meena  Chennai     85  Data Science
4          3        Kumar  Chennai     76   Mathematics

Student Scholarship Filter Completed!

In [2]:

# Problem 2: Employee Salary Audit

import sqlite3
import pandas as pd

# Step 1: Connect to database
conn = sqlite3.connect("employee_salary_audit.db")
cursor = conn.cursor()

# Step 2: Create EMPLOYEE table
cursor.execute("""
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EmpID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Dept TEXT,
    Salary INTEGER,
    City TEXT
)
""")

# Step 3: Insert 10 employee records
employees = [
    (1, 'Arun', 'IT', 45000, 'Coimbatore'),
    (2, 'Priya', 'HR', 35000, 'Salem'),
    (3, 'Kumar', 'IT', 75000, 'Chennai'),
    (4, 'Divya', 'Finance', 50000, 'Salem'),
    (5, 'Ravi', 'IT', 28000, 'Madurai'),
    (6, 'Meena', 'IT', 60000, 'Coimbatore'),
    (7, 'Suresh', 'HR', 40000, 'Chennai'),
    (8, 'Anu', 'Finance', 25000, 'Coimbatore'),
    (9, 'Bala', 'IT', 80000, 'Salem'),
    (10, 'Nila', 'Marketing', 55000, 'Trichy')
]

cursor.executemany("""
INSERT OR REPLACE INTO EMPLOYEE
(EmpID, Name, Dept, Salary, City)
VALUES (?, ?, ?, ?, ?)
""", employees)

conn.commit()

# Step 4: Display all employees
print("ALL EMPLOYEE RECORDS")
display(pd.read_sql_query(
    "SELECT * FROM EMPLOYEE", conn
))

# Step 5: Display DISTINCT cities
print("DISTINCT CITIES")
display(pd.read_sql_query("""
SELECT DISTINCT City
FROM EMPLOYEE
ORDER BY City ASC
""", conn))

# Step 6: Employee Salary Audit - TOP 3
print("TOP 3 EMPLOYEES AFTER FILTERING")
display(pd.read_sql_query("""
SELECT
    EmpID,
    Name,
    Dept,
    Salary AS Monthly_Salary,
    City
FROM EMPLOYEE
WHERE
    (
        Dept = 'IT'
        AND Salary BETWEEN 30000 AND 80000
    )
    OR City IN ('Coimbatore', 'Salem')
    AND NOT Dept = 'HR'
ORDER BY Salary ASC
LIMIT 3
""", conn))

conn.close()

print("Employee Salary Audit Completed!")

ALL EMPLOYEE RECORDS

   EmpID    Name       Dept  Salary        City
0      1    Arun         IT   45000  Coimbatore
1      2   Priya         HR   35000       Salem
2      3   Kumar         IT   75000     Chennai
3      4   Divya    Finance   50000       Salem
4      5    Ravi         IT   28000     Madurai
5      6   Meena         IT   60000  Coimbatore
6      7  Suresh         HR   40000     Chennai
7      8     Anu    Finance   25000  Coimbatore
8      9    Bala         IT   80000       Salem
9     10    Nila  Marketing   55000      Trichy

DISTINCT CITIES

         City
0     Chennai
1  Coimbatore
2     Madurai
3       Salem
4      Trichy

TOP 3 EMPLOYEES AFTER FILTERING

   EmpID   Name     Dept  Monthly_Salary        City
0      8    Anu  Finance           25000  Coimbatore
1      1   Arun       IT           45000  Coimbatore
2      4  Divya  Finance           50000       Salem

Employee Salary Audit Completed!

In [3]:

# Problem 3: Product Discount Check

import sqlite3
import pandas as pd

# Step 1: Connect to database
conn = sqlite3.connect("product_discount.db")
cursor = conn.cursor()

# Step 2: Create PRODUCT table
cursor.execute("""
CREATE TABLE IF NOT EXISTS PRODUCT (
    ProductID INTEGER PRIMARY KEY,
    ProductName TEXT NOT NULL,
    Category TEXT,
    Price INTEGER,
    Stock INTEGER
)
""")

# Step 3: Insert 8 products
products = [
    (1, 'Laptop', 'Electronics', 45000, 10),
    (2, 'Headphones', 'Electronics', 2500, 20),
    (3, 'Mixer', 'Appliances', 3500, 8),
    (4, 'Smart Watch', 'Electronics', 5000, 4),
    (5, 'Microwave', 'Appliances', 4800, 12),
    (6, 'Keyboard', 'Electronics', 1500, 0),
    (7, 'Toaster', 'Appliances', 2200, 15),
    (8, 'Camera', 'Electronics', 7000, 9)
]

cursor.executemany("""
INSERT OR REPLACE INTO PRODUCT
(ProductID, ProductName, Category, Price, Stock)
VALUES (?, ?, ?, ?, ?)
""", products)

conn.commit()

# Step 4: Display all products
print("ALL PRODUCT RECORDS")
display(pd.read_sql_query(
    "SELECT * FROM PRODUCT", conn
))

# Step 5: Display DISTINCT categories
print("DISTINCT CATEGORIES")
display(pd.read_sql_query("""
SELECT DISTINCT Category
FROM PRODUCT
ORDER BY Category ASC
""", conn))

# Step 6: TOP 4 expensive products after filtering
print("TOP 4 PRODUCTS")
display(pd.read_sql_query("""
SELECT
    ProductID,
    ProductName AS Item_Name,
    Category,
    Price,
    Stock
FROM PRODUCT
WHERE
    Price BETWEEN 1000 AND 5000
    AND Category IN ('Electronics', 'Appliances')
    AND Stock NOT BETWEEN 0 AND 5
ORDER BY Price DESC
LIMIT 4
""", conn))

conn.close()

print("Product Discount Check Completed!")

ALL PRODUCT RECORDS

   ProductID  ProductName     Category  Price  Stock
0          1       Laptop  Electronics  45000     10
1          2   Headphones  Electronics   2500     20
2          3        Mixer   Appliances   3500      8
3          4  Smart Watch  Electronics   5000      4
4          5    Microwave   Appliances   4800     12
5          6     Keyboard  Electronics   1500      0
6          7      Toaster   Appliances   2200     15
7          8       Camera  Electronics   7000      9

DISTINCT CATEGORIES

      Category
0   Appliances
1  Electronics

TOP 4 PRODUCTS

   ProductID   Item_Name     Category  Price  Stock
0          5   Microwave   Appliances   4800     12
1          3       Mixer   Appliances   3500      8
2          2  Headphones  Electronics   2500     20
3          7     Toaster   Appliances   2200     15

Product Discount Check Completed!

In [4]:

# Problem 4: Hospital Patient Priority List

import sqlite3
import pandas as pd

# Step 1: Connect to database
conn = sqlite3.connect("hospital_patient.db")
cursor = conn.cursor()

# Step 2: Create PATIENT table
cursor.execute("""
CREATE TABLE IF NOT EXISTS PATIENT (
    PatientID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Age INTEGER,
    City TEXT,
    Disease TEXT,
    BillAmount INTEGER
)
""")

# Step 3: Insert 10 patient records
patients = [
    (1, 'Arun', 35, 'Trichy', 'Diabetes', 25000),
    (2, 'Priya', 45, 'Tanjore', 'Heart Disease', 65000),
    (3, 'Kumar', 28, 'Trichy', 'Asthma', 12000),
    (4, 'Divya', 60, 'Madurai', 'Cold', 5000),
    (5, 'Ravi', 52, 'Tanjore', 'Kidney Disease', 85000),
    (6, 'Meena', 40, 'Trichy', 'Fever', 3000),
    (7, 'Suresh', 70, 'Tanjore', 'Diabetes', 45000),
    (8, 'Anu', 32, 'Trichy', 'Asthma', 18000),
    (9, 'Bala', 65, 'Tanjore', 'Heart Disease', 95000),
    (10, 'Nila', 55, 'Trichy', 'Liver Disease', 55000)
]

cursor.executemany("""
INSERT OR REPLACE INTO PATIENT
(PatientID, Name, Age, City, Disease, BillAmount)
VALUES (?, ?, ?, ?, ?, ?)
""", patients)

conn.commit()

# Step 4: Display all patient records
print("ALL PATIENT RECORDS")
display(pd.read_sql_query(
    "SELECT * FROM PATIENT", conn
))

# Step 5: Display DISTINCT diseases
print("DISTINCT DISEASES")
display(pd.read_sql_query("""
SELECT DISTINCT Disease
FROM PATIENT
ORDER BY Disease ASC
""", conn))

# Step 6: TOP 6 highest bills after filtering
print("TOP 6 PATIENTS BY BILL AMOUNT")
display(pd.read_sql_query("""
SELECT
    PatientID,
    Name,
    Age,
    City,
    Disease,
    BillAmount AS Total_Bill
FROM PATIENT
WHERE
    Age BETWEEN 30 AND 70
    AND Disease NOT IN ('Cold', 'Fever')
    AND (City = 'Trichy' OR City = 'Tanjore')
ORDER BY BillAmount DESC
LIMIT 6
""", conn))

conn.close()

print("Hospital Patient Priority List Completed!")

ALL PATIENT RECORDS

   PatientID    Name  Age     City         Disease  BillAmount
0          1    Arun   35   Trichy        Diabetes       25000
1          2   Priya   45  Tanjore   Heart Disease       65000
2          3   Kumar   28   Trichy          Asthma       12000
3          4   Divya   60  Madurai            Cold        5000
4          5    Ravi   52  Tanjore  Kidney Disease       85000
5          6   Meena   40   Trichy           Fever        3000
6          7  Suresh   70  Tanjore        Diabetes       45000
7          8     Anu   32   Trichy          Asthma       18000
8          9    Bala   65  Tanjore   Heart Disease       95000
9         10    Nila   55   Trichy   Liver Disease       55000

DISTINCT DISEASES

          Disease
0          Asthma
1            Cold
2        Diabetes
3           Fever
4   Heart Disease
5  Kidney Disease
6   Liver Disease

TOP 6 PATIENTS BY BILL AMOUNT

   PatientID    Name  Age     City         Disease  Total_Bill
0          9    Bala   65  Tanjore   Heart Disease       95000
1          5    Ravi   52  Tanjore  Kidney Disease       85000
2          2   Priya   45  Tanjore   Heart Disease       65000
3         10    Nila   55   Trichy   Liver Disease       55000
4          7  Suresh   70  Tanjore        Diabetes       45000
5          1    Arun   35   Trichy        Diabetes       25000

Hospital Patient Priority List Completed!