In [8]:
#Problem statmwnt 1.Student Management Database
#Step 1: Create Database and Table
import sqlite3

# Connect to SQLite database
conn = sqlite3.connect(':memory:')  # in-memory DB
cursor = conn.cursor()

# Create Students table with constraints
cursor.execute("""
CREATE TABLE Students (
    student_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER CHECK(age >= 18),
    email TEXT UNIQUE,
    course TEXT DEFAULT 'Data Science',
    fees_paid REAL CHECK(fees_paid >= 0)
)
""")

print("Students table created successfully!")
#Step 2: Insert Valid Records
cursor.execute("""
INSERT INTO Students (student_id, name, age, email, fees_paid)
VALUES (1, 'Arun', 22, 'arun@gmail.com', 25000)
""")

cursor.execute("""
INSERT INTO Students (student_id, name, age, email, course, fees_paid)
VALUES (2, 'Divya', 25, 'divya@gmail.com', 'AI', 30000)
""")

conn.commit()
print("Valid records inserted successfully!")
#Step 3: Try Inserting Invalid Records (Constraint Violations)
try:
    cursor.execute("""
    INSERT INTO Students VALUES (3, 'Kiran', 16, 'kiran@gmail.com', 'ML', 20000)
    """)
except Exception as e:
    print("Error:", e)
try:
    cursor.execute("""
    INSERT INTO Students VALUES (4, 'Ravi', 23, 'arun@gmail.com', 'Python', 15000)
    """)
except Exception as e:
    print("Error:", e)
try:
    cursor.execute("""
    INSERT INTO Students VALUES (5, 'Meena', 24, 'meena@gmail.com', 'SQL', -500)
    """)
except Exception as e:
    print("Error:", e)
#Step 4: Display Final Table Data
cursor.execute("SELECT * FROM Students")
rows = cursor.fetchall()

for row in rows:
    print(row)

Students table created successfully!
Valid records inserted successfully!
Error: CHECK constraint failed: age >= 18
Error: UNIQUE constraint failed: Students.email
Error: CHECK constraint failed: fees_paid >= 0
(1, 'Arun', 22, 'arun@gmail.com', 'Data Science', 25000.0)
(2, 'Divya', 25, 'divya@gmail.com', 'AI', 30000.0)

In [7]:
#Problem statement 2 employees payroll system
#Step 1: Create Database and Employees Table
import sqlite3

# Connect to SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create Employees table with constraints
cursor.execute("""
CREATE TABLE Employees (
    emp_id INTEGER PRIMARY KEY AUTOINCREMENT,
    emp_name TEXT NOT NULL,
    department TEXT CHECK(department IN ('HR','IT','Finance','Marketing')),
    salary REAL CHECK(salary > 15000),
    phone TEXT UNIQUE,
    joining_date TEXT NOT NULL
)
""")

print("Employees table created successfully!")
#Step 2: Insert Valid Records
cursor.execute("""
INSERT INTO Employees (emp_name, department, salary, phone, joining_date)
VALUES ('Suresh', 'IT', 35000, '9876543210', '2024-06-01')
""")

cursor.execute("""
INSERT INTO Employees (emp_name, department, salary, phone, joining_date)
VALUES ('Anitha', 'HR', 28000, '9876543211', '2023-09-15')
""")

conn.commit()
print("Valid employee records inserted!")
#Step 3: Insert Invalid Records (Constraint Violations)
try:
    cursor.execute("""
    INSERT INTO Employees (emp_name, department, salary, phone, joining_date)
    VALUES ('Rahul', 'Sales', 30000, '9876543212', '2024-01-10')
    """)
except Exception as e:
    print("Error:", e)
try:
    cursor.execute("""
    INSERT INTO Employees (emp_name, department, salary, phone, joining_date)
    VALUES ('Meera', 'Finance', 12000, '9876543213', '2024-02-20')
    """)
except Exception as e:
    print("Error:", e)
try:
    cursor.execute("""
    INSERT INTO Employees (emp_name, department, salary, phone, joining_date)
    VALUES ('Karthik', 'Marketing', 25000, '9876543210', '2024-03-05')
    """)
except Exception as e:
    print("Error:", e)
#Step 4: Display Stored Data
cursor.execute("SELECT * FROM Employees")
rows = cursor.fetchall()

for row in rows:
    print(row)

Employees table created successfully!
Valid employee records inserted!
Error: CHECK constraint failed: department IN ('HR','IT','Finance','Marketing')
Error: CHECK constraint failed: salary > 15000
Error: UNIQUE constraint failed: Employees.phone
(1, 'Suresh', 'IT', 35000.0, '9876543210', '2024-06-01')
(2, 'Anitha', 'HR', 28000.0, '9876543211', '2023-09-15')

In [3]:
# PROBLEM STATEMENT 3 — Transaction Management Database
# STEP 1: IMPORT LIBRARIES
import sqlite3
import pandas as pd

# STEP 2: CREATE DATABASE CONNECTION
conn = sqlite3.connect("bank_transactions_new.db")
conn.execute("PRAGMA foreign_keys = ON")
cursor = conn.cursor()

# STEP 3: CREATE BANK_TRANSACTIONS TABLE
cursor.execute("""
CREATE TABLE IF NOT EXISTS Bank_Transactions (
    transaction_id INTEGER PRIMARY KEY,

    account_number TEXT NOT NULL
        CHECK (
            length(account_number) = 10
            AND account_number NOT GLOB '*[^0-9]*'
        ),

    transaction_type TEXT NOT NULL
        CHECK (
            transaction_type IN
            ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')
        ),

    amount REAL NOT NULL
        CHECK (amount > 0),

    transaction_date TEXT NOT NULL
        CHECK (
            date(transaction_date) IS NOT NULL
            AND date(transaction_date) = transaction_date
        ),

    balance_after REAL NOT NULL
        CHECK (balance_after >= 0),

    status TEXT NOT NULL
        CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING')),

    CHECK (
        transaction_type != 'WITHDRAWAL'
        OR amount <= 50000
    )
)
""")

# STEP 4: INSERT VALID TRANSACTION DATA
transactions = [
    (1, '1234567890', 'DEPOSIT', 20000,
     '2026-10-20', 20000, 'SUCCESS'),

    (2, '1234567890', 'WITHDRAWAL', 5000,
     '2026-10-21', 15000, 'SUCCESS'),

    (3, '9876543210', 'DEPOSIT', 40000,
     '2026-10-22', 40000, 'SUCCESS'),

    (4, '9876543210', 'TRANSFER', 10000,
     '2026-10-23', 30000, 'SUCCESS'),

    (5, '1122334455', 'DEPOSIT', 15000,
     '2026-10-24', 15000, 'PENDING'),

    (6, '1122334455', 'WITHDRAWAL', 2000,
     '2026-10-25', 13000, 'SUCCESS')
]

cursor.executemany("""
INSERT INTO Bank_Transactions (
    transaction_id,
    account_number,
    transaction_type,
    amount,
    transaction_date,
    balance_after,
    status
)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", transactions)

conn.commit()

# STEP 5: DISPLAY ALL TRANSACTIONS
print("ALL BANK TRANSACTIONS")

display(pd.read_sql_query("""
SELECT * FROM Bank_Transactions
ORDER BY transaction_id
""", conn))

# STEP 6: DISPLAY SUCCESSFUL TRANSACTIONS
print("SUCCESSFUL TRANSACTIONS")

display(pd.read_sql_query("""
SELECT *
FROM Bank_Transactions
WHERE status = 'SUCCESS'
""", conn))

# STEP 7: TRANSACTION TYPE-WISE REPORT
print("TRANSACTION TYPE SUMMARY")

display(pd.read_sql_query("""
SELECT
    transaction_type,
    COUNT(*) AS total_transactions,
    SUM(amount) AS total_amount
FROM Bank_Transactions
GROUP BY transaction_type
""", conn))

# STEP 8: ACCOUNT-WISE TRANSACTION SUMMARY
print("ACCOUNT-WISE SUMMARY")

display(pd.read_sql_query("""
SELECT
    account_number,
    COUNT(*) AS total_transactions,
    SUM(amount) AS total_transaction_amount,
    MAX(balance_after) AS latest_recorded_balance
FROM Bank_Transactions
GROUP BY account_number
""", conn))

# STEP 9: CHECK FOR FAILED OR PENDING TRANSACTIONS
print("FAILED OR PENDING TRANSACTIONS")

display(pd.read_sql_query("""
SELECT *
FROM Bank_Transactions
WHERE status IN ('FAILED', 'PENDING')
""", conn))

# STEP 10: CLOSE DATABASE
conn.close()

print("Transaction Management Database Completed!")

ALL BANK TRANSACTIONS

,transaction_id,account_number,transaction_type,amount,transaction_date,balance_after,status
0,1,1234567890,DEPOSIT,20000.0,2026-10-20,20000.0,SUCCESS
1,2,1234567890,WITHDRAWAL,5000.0,2026-10-21,15000.0,SUCCESS
2,3,9876543210,DEPOSIT,40000.0,2026-10-22,40000.0,SUCCESS
3,4,9876543210,TRANSFER,10000.0,2026-10-23,30000.0,SUCCESS
4,5,1122334455,DEPOSIT,15000.0,2026-10-24,15000.0,PENDING
5,6,1122334455,WITHDRAWAL,2000.0,2026-10-25,13000.0,SUCCESS

SUCCESSFUL TRANSACTIONS

,transaction_id,account_number,transaction_type,amount,transaction_date,balance_after,status
0,1,1234567890,DEPOSIT,20000.0,2026-10-20,20000.0,SUCCESS
1,2,1234567890,WITHDRAWAL,5000.0,2026-10-21,15000.0,SUCCESS
2,3,9876543210,DEPOSIT,40000.0,2026-10-22,40000.0,SUCCESS
3,4,9876543210,TRANSFER,10000.0,2026-10-23,30000.0,SUCCESS
4,6,1122334455,WITHDRAWAL,2000.0,2026-10-25,13000.0,SUCCESS

TRANSACTION TYPE SUMMARY

  transaction_type  total_transactions  total_amount
0          DEPOSIT                   3       75000.0
1         TRANSFER                   1       10000.0
2       WITHDRAWAL                   2        7000.0

ACCOUNT-WISE SUMMARY

,account_number,total_transactions,total_transaction_amount,latest_recorded_balance
0,1122334455,2,17000.0,15000.0
1,1234567890,2,25000.0,20000.0
2,9876543210,2,50000.0,40000.0

FAILED OR PENDING TRANSACTIONS

,transaction_id,account_number,transaction_type,amount,transaction_date,balance_after,status
0,5,1122334455,DEPOSIT,15000.0,2026-10-24,15000.0,PENDING

Transaction Management Database Completed!

In [4]:
# PROBLEM STATEMENT 4 — Online Examination System
# STEP 1: IMPORT LIBRARIES
import sqlite3
import pandas as pd
from datetime import date

# STEP 2: CREATE DATABASE CONNECTION
conn = sqlite3.connect("online_exam.db")
cursor = conn.cursor()

# STEP 3: CREATE TABLE
cursor.execute("""
CREATE TABLE IF NOT EXISTS Exam_Registrations (
    registration_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    exam_code TEXT NOT NULL
        CHECK (
            length(exam_code) = 6
            AND exam_code GLOB 'EXM[0-9][0-9][0-9]'
        ),
    exam_date TEXT NOT NULL,
    marks INTEGER
        CHECK (marks BETWEEN 0 AND 100),
    attempt_number INTEGER NOT NULL
        CHECK (attempt_number BETWEEN 1 AND 3),
    result_status TEXT NOT NULL
        CHECK (result_status IN ('PASS', 'FAIL', 'ABSENT')),
    UNIQUE (student_id, exam_code)
)
""")

# STEP 4: VALIDATE EXAM DATE
def valid_exam_date(exam_date):
    try:
        parsed_date = date.fromisoformat(exam_date)
        return parsed_date > date.today()
    except ValueError:
        return False

# STEP 5: SAMPLE REGISTRATION DATA
registrations = [
    (101, 'EXM101', '2026-12-15', 85, 1, 'PASS'),
    (102, 'EXM102', '2026-12-20', 72, 1, 'PASS'),
    (103, 'EXM103', '2027-01-10', 45, 2, 'FAIL'),
    (104, 'EXM104', '2027-01-15', None, 1, 'ABSENT'),
    (105, 'EXM105', '2027-02-01', 90, 3, 'PASS')
]

# STEP 6: INSERT VALID REGISTRATIONS
for student_id, exam_code, exam_date, marks, attempt, status in registrations:

    if not valid_exam_date(exam_date):
        print("Invalid exam date:", exam_date)
        continue

    try:
        cursor.execute("""
        INSERT INTO Exam_Registrations
        (student_id, exam_code, exam_date,
         marks, attempt_number, result_status)
        VALUES (?, ?, ?, ?, ?, ?)
        """, (
            student_id, exam_code, exam_date,
            marks, attempt, status
        ))
        print("Registration added for student:", student_id)

    except sqlite3.IntegrityError as error:
        print("Registration rejected:", error)

conn.commit()

# STEP 7: DISPLAY ALL REGISTRATIONS
print("\nALL EXAM REGISTRATIONS")

display(pd.read_sql_query("""
SELECT * FROM Exam_Registrations
ORDER BY registration_id
""", conn))

# STEP 8: DISPLAY PASS RESULTS
print("\nPASSED STUDENTS")

display(pd.read_sql_query("""
SELECT student_id, exam_code, marks, result_status
FROM Exam_Registrations
WHERE result_status = 'PASS'
""", conn))

# STEP 9: DISPLAY FAIL RESULTS
print("\nFAILED STUDENTS")

display(pd.read_sql_query("""
SELECT student_id, exam_code, marks, result_status
FROM Exam_Registrations
WHERE result_status = 'FAIL'
""", conn))

# STEP 10: DISPLAY EXAM-WISE SUMMARY
print("\nEXAM-WISE SUMMARY")

display(pd.read_sql_query("""
SELECT
    exam_code,
    COUNT(*) AS total_registrations,
    AVG(marks) AS average_marks
FROM Exam_Registrations
GROUP BY exam_code
""", conn))

# STEP 11: CHECK REGISTRATION COUNTS
print("\nSTUDENT REGISTRATION DETAILS")

display(pd.read_sql_query("""
SELECT
    student_id,
    COUNT(*) AS total_exams,
    MAX(attempt_number) AS highest_attempt
FROM Exam_Registrations
GROUP BY student_id
""", conn))

# STEP 12: CLOSE DATABASE
conn.close()

print("\nOnline Examination System Completed!")

Registration added for student: 101
Registration added for student: 102
Registration added for student: 103
Registration added for student: 104
Registration added for student: 105

ALL EXAM REGISTRATIONS

,registration_id,student_id,exam_code,exam_date,marks,attempt_number,result_status
0,1,101,EXM101,2026-12-15,85.0,1,PASS
1,2,102,EXM102,2026-12-20,72.0,1,PASS
2,3,103,EXM103,2027-01-10,45.0,2,FAIL
3,4,104,EXM104,2027-01-15,NaN,1,ABSENT
4,5,105,EXM105,2027-02-01,90.0,3,PASS

PASSED STUDENTS

   student_id exam_code  marks result_status
0         101    EXM101     85          PASS
1         102    EXM102     72          PASS
2         105    EXM105     90          PASS

FAILED STUDENTS

   student_id exam_code  marks result_status
0         103    EXM103     45          FAIL

EXAM-WISE SUMMARY

  exam_code  total_registrations  average_marks
0    EXM101                    1           85.0
1    EXM102                    1           72.0
2    EXM103                    1           45.0
3    EXM104                    1            NaN
4    EXM105                    1           90.0

STUDENT REGISTRATION DETAILS

   student_id  total_exams  highest_attempt
0         101            1                1
1         102            1                1
2         103            1                2
3         104            1                1
4         105            1                3

Online Examination System Completed!